"""Add exhausted_models JSONB to reconciliation_runs

Revision ID: 3de6cf028dad
Revises: e510bc568a88
Create Date: 2026-08-29 10:59:56.194498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3de6cf028dad'
down_revision: Union[str, Sequence[str], None] = 'e510bc568a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_runs', sa.Column('exhausted_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of models that hit daily quota exhaustion'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_runs', 'exhausted_models')
    # ### end Alembic commands ###
