"""Initial schema

Revision ID: d05bb5c209fa
Revises: 
Create Date: 2026-08-29 10:36:46.126133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd05bb5c209fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False, comment='upi / card / netbanking / wallet'),
    sa.Column('mdr_basis_points', sa.Integer(), nullable=False, comment='MDR rate in basis points (e.g. 200 = 2%)'),
    sa.Column('gst_rate_basis_points', sa.Integer(), nullable=False, comment='GST rate on fee in basis points (1800 = 18%)'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_schedule_merchant_id'), 'fee_schedule', ['merchant_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=True, comment='SHA-256 hex digest of source file bytes'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'PARTIAL', name='run_status_enum', create_constraint=True), nullable=False),
    sa.Column('eval_mode', sa.Boolean(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('match_rate', sa.Float(), nullable=True, comment='Match rate as decimal 0.0–1.0 (metric only, never used for money)'),
    sa.Column('ledger_leak_variance_paise', sa.BigInteger(), nullable=True, comment='Global conservation residual in paise (signed); 0 = balanced'),
    sa.Column('processing_ms', sa.BigInteger(), nullable=True, comment='Total wall-clock ms for batch'),
    sa.Column('run_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_source_checksum'), 'reconciliation_runs', ['source_checksum'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_txn_id', sa.String(length=64), nullable=False, comment='Bank-assigned transaction reference'),
    sa.Column('raw_narration', sa.Text(), nullable=True, comment='Original CBS narration string (untouched)'),
    sa.Column('canonical_utr', sa.String(length=64), nullable=True, comment='Normalised UTR extracted by regex; Hop 2 join key'),
    sa.Column('direction', sa.Enum('CREDIT', 'DEBIT', name='bank_txn_direction_enum', create_constraint=True), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False, comment='Credit or debit amount in paise'),
    sa.Column('bank_charges_paise', sa.BigInteger(), nullable=False, comment='Bank-side charges (deducted from credit)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('txn_date', sa.DateTime(timezone=True), nullable=False, comment='Transaction posting date'),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_txn_id'), 'bank_transactions', ['bank_txn_id'], unique=True)
    op.create_index(op.f('ix_bank_transactions_canonical_utr'), 'bank_transactions', ['canonical_utr'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False, comment='Dispute debit amount in paise (positive; negated at allocation)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('dispute_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_dispute_id'), 'disputes', ['dispute_id'], unique=True)
    op.create_index(op.f('ix_disputes_order_id'), 'disputes', ['order_id'], unique=False)
    op.create_table('exception_staging',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('TIMING_SETTLEMENT_FLOAT', 'GATEWAY_FEE_MISMATCH', 'UNRECONCILED_BANK_FEE', 'SPLIT_PAYOUT_PARTIAL_DROP', 'CHARGEBACK_DEBIT_UNMATCHED', 'CURRENCY_CONVERSION_VARIANCE', 'SUSPICIOUS_ROUND_NUMBER_DRAIN', 'MISSING_SETTLEMENT_RECORD', 'UNMAPPED_BANK_DEPOSIT', 'ESCALATED_UNRESOLVED', 'UNACCOUNTED_LEDGER_LEAK', name='exception_category_enum', create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='exception_severity_enum', create_constraint=True), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True, comment='Source entity type if applicable'),
    sa.Column('entity_id', sa.String(length=64), nullable=True, comment='Source entity ID if applicable'),
    sa.Column('variance_paise', sa.BigInteger(), nullable=True, comment='Signed variance / residual in paise (e.g. leak delta)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured diagnostic metadata (reasoning, evidence, etc.)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_staging_reconciliation_run_id'), 'exception_staging', ['reconciliation_run_id'], unique=False)
    op.create_table('match_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('EXACT', 'FUZZY', 'LLM', 'HUMAN', name='match_tier_enum', create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='0.0–1.0 match confidence (metric only, never money)'),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='True iff IndependentVerifier passed integer paise check'),
    sa.Column('residual_paise', sa.BigInteger(), nullable=False, comment='Signed residual after verification (0 = perfect balance)'),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('cited_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hitl_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'RESOLVED', 'EVAL_BYPASSED', name='hitl_status_enum', create_constraint=True), nullable=False),
    sa.Column('original_tier_hint', sa.String(length=128), nullable=True, comment='Provenance tag if demoted (e.g. exact_id_conservation_failed)'),
    sa.Column('processing_ms', sa.BigInteger(), nullable=True, comment='Wall-clock ms for this match group'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_groups_reconciliation_run_id'), 'match_groups', ['reconciliation_run_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False, comment='Razorpay order_id (e.g. order_xxx)'),
    sa.Column('payment_id', sa.String(length=64), nullable=True, comment='Razorpay payment_id (e.g. pay_xxx)'),
    sa.Column('transaction_type', sa.Enum('PAYMENT', 'AUTHORIZATION', name='transaction_type_enum', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'SETTLED', 'REFUNDED', 'FAILED', name='order_status_enum', create_constraint=True), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True, comment='upi / card / netbanking / wallet'),
    sa.Column('gross_amount_paise', sa.BigInteger(), nullable=False, comment='Total order amount in paise'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_payment_id'), 'orders', ['payment_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('refund_id', sa.String(length=64), nullable=False, comment='Razorpay refund_id (e.g. rfnd_xxx)'),
    sa.Column('order_id', sa.String(length=64), nullable=False, comment='FK-like reference to orders.order_id'),
    sa.Column('payment_id', sa.String(length=64), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False, comment='Refund amount in paise (positive value; negated at allocation time)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refund_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_refund_id'), 'refunds', ['refund_id'], unique=True)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.String(length=64), nullable=False, comment='Razorpay settlement_id (e.g. setl_xxx)'),
    sa.Column('utr', sa.String(length=64), nullable=True, comment='Unique Transaction Reference for bank payout'),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSED', 'SETTLED', 'FAILED', name='settlement_status_enum', create_constraint=True), nullable=False),
    sa.Column('gross_amount_paise', sa.BigInteger(), nullable=False, comment='Total gross settlement before fees'),
    sa.Column('fee_base_paise', sa.BigInteger(), nullable=False, comment='Platform / MDR fee in paise (pre-GST)'),
    sa.Column('fee_tax_gst_paise', sa.BigInteger(), nullable=False, comment='18% GST on fee_base in paise'),
    sa.Column('net_amount_paise', sa.BigInteger(), nullable=False, comment='Net payout = gross - fee_base - fee_tax_gst'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settlement_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True, comment='Bank value date for T+2 float calculation'),
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_settlement_id'), 'settlements', ['settlement_id'], unique=True)
    op.create_index(op.f('ix_settlements_utr'), 'settlements', ['utr'], unique=False)
    op.create_table('match_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_group_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('ORDER', 'REFUND', 'DISPUTE_DEBIT', 'SETTLEMENT', 'BANK_TRANSACTION', name='entity_type_enum', create_constraint=True), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False, comment='References the domain ID in the source table (order_id, refund_id, etc.)'),
    sa.Column('allocated_paise', sa.BigInteger(), nullable=False, comment='Signed allocation amount in paise; negative for refunds/clawbacks'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_group_id'], ['match_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_allocation_entity')
    )
    op.create_index('ix_allocation_entity_lookup', 'match_allocations', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_match_allocations_match_group_id'), 'match_allocations', ['match_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_allocations_match_group_id'), table_name='match_allocations')
    op.drop_index('ix_allocation_entity_lookup', table_name='match_allocations')
    op.drop_table('match_allocations')
    op.drop_index(op.f('ix_settlements_utr'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settlement_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_refunds_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_orders_payment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_match_groups_reconciliation_run_id'), table_name='match_groups')
    op.drop_table('match_groups')
    op.drop_index(op.f('ix_exception_staging_reconciliation_run_id'), table_name='exception_staging')
    op.drop_table('exception_staging')
    op.drop_index(op.f('ix_disputes_order_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_dispute_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_bank_transactions_canonical_utr'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_txn_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_reconciliation_runs_source_checksum'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_fee_schedule_merchant_id'), table_name='fee_schedule')
    op.drop_table('fee_schedule')
    # ### end Alembic commands ###
