"""Add model_used to match_groups

Revision ID: e510bc568a88
Revises: d05bb5c209fa
Create Date: 2026-08-29 10:49:33.321297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e510bc568a88'
down_revision: Union[str, Sequence[str], None] = 'd05bb5c209fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_groups', sa.Column('model_used', sa.String(length=128), nullable=True, comment='Model that successfully resolved the cluster'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_groups', 'model_used')
    # ### end Alembic commands ###
